#@data/values
---
petclinic:
  host: 
  image:
  configRepo: https://github.com/tanzu-end-to-end/spring-petclinic-config
  codeRepo: https://github.com/cdelashmutt-pivotal/spring-petclinic
  wavefront:
    applicationName: 
    uri: https://vmware.wavefront.com
    apiToken: 48b7b6a9-74ef-41f5-8002-f18dec9f82e2
    deployEventName: 
  tbs:
    namespace:
  ingressSecret: eduk8s/eduk8s-cert-tls
  signingSecret: ""
commonSecrets:
  harborDomain: 
  artifactoryDomain: 
  notaryUrl: https://notary.tools.pez.aws.grogscave.net
  harborUser: admin
  harborPassword: Harbor12345
  kubeconfigBuildServer:
  kubeconfigAppServer:
  concourseHelperImage: 
  concourseUri: 
  concourseUser: test
  concoursePassword: test